mujoco:
  experiment_name: "h12_locomotion"

  sim_dt: 0.001
  render_dt: 0.02
  decimation: 20
  episode_length: 5

  enable_GUI: True
  fix_base: False
  real_time: False
  enable_keyboard: True
  check_violations: False
  safety_checker_verbose: False
  elastic_band: False

real:
  net_interface: eth0
  control_dt: 0.02
  use_mujoco: True

joints:
  - name: left_hip_yaw
    kp: 200
    kd: 2.5
    default_joint_pos: 0.0
    enabled: true
  - name: left_hip_pitch
    kp: 200
    kd: 2.5
    default_joint_pos: -0.16
    enabled: true
  - name: left_hip_roll
    kp: 200
    kd: 2.5
    default_joint_pos: 0.0
    enabled: true
  - name: left_knee
    kp: 300
    kd: 4.0
    default_joint_pos: 0.36
    enabled: true
  - name: left_ankle_pitch
    kp: 40
    kd: 2.0
    default_joint_pos: -0.2
    enabled: true
  - name: left_ankle_roll
    kp: 40
    kd: 2.0
    default_joint_pos: 0.0
    enabled: true
  - name: right_hip_yaw
    kp: 200
    kd: 2.5
    default_joint_pos: 0.0
    enabled: true
  - name: right_hip_pitch
    kp: 200
    kd: 2.5
    default_joint_pos: -0.16
    enabled: true
  - name: right_hip_roll
    kp: 200
    kd: 2.5
    default_joint_pos: 0.0
    enabled: true
  - name: right_knee
    kp: 300
    kd: 4.0
    default_joint_pos: 0.36
    enabled: true
  - name: right_ankle_pitch
    kp: 40
    kd: 2.0
    default_joint_pos: -0.2
    enabled: true
  - name: right_ankle_roll
    kp: 40
    kd: 2.0
    default_joint_pos: 0.0
    enabled: true
  - name: torso
    kp: 300
    kd: 3.0
    default_joint_pos: 0.0
    enabled: false
  - name: left_shoulder_pitch
    kp: 120
    kd: 2.0
    default_joint_pos: 0.0
    enabled: false
  - name: left_shoulder_roll
    kp: 120
    kd: 2.0
    default_joint_pos: 0.0
    enabled: false
  - name: left_shoulder_yaw
    kp: 120
    kd: 2.0
    default_joint_pos: 0.0
    enabled: false
  - name: left_elbow
    kp: 80
    kd: 1.0
    default_joint_pos: 0.0
    enabled: false
  - name: left_wrist_roll
    kp: 80
    kd: 1.0
    default_joint_pos: 0.0
    enabled: false
  - name: left_wrist_pitch
    kp: 80
    kd: 1.0
    default_joint_pos: 0.0
    enabled: false
  - name: left_wrist_yaw
    kp: 80
    kd: 1.0
    default_joint_pos: 0.0
    enabled: false
  - name: right_shoulder_pitch
    kp: 120
    kd: 2.0
    default_joint_pos: 0.0
    enabled: false
  - name: right_shoulder_roll
    kp: 120
    kd: 2.0
    default_joint_pos: 0.0
    enabled: false
  - name: right_shoulder_yaw
    kp: 120
    kd: 2.0
    default_joint_pos: 0.0
    enabled: false
  - name: right_elbow
    kp: 80
    kd: 1.0
    default_joint_pos: 0.0
    enabled: false
  - name: right_wrist_roll
    kp: 80
    kd: 1.0
    default_joint_pos: 0.0
    enabled: false
  - name: right_wrist_pitch
    kp: 80
    kd: 1.0
    default_joint_pos: 0.0
    enabled: false
  - name: right_wrist_yaw
    kp: 80
    kd: 1.0
    default_joint_pos: 0.0
    enabled: false
